name: Build and Push Docker Image 

on:
  pull_request:
    branches:
      - master

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up QEMU
          run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        - name: Log in to Docker Hub
          run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin

        - name: Build and push Docker image
          run: |
            docker buildx create --use
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              -t $DOCKER_USERNAME/private:back-bond \
              --push .

        - name: Clean up
          run: docker buildx rm