language: java
jdk:
  - openjdk17

#jobs:
  #include:
    #- stage: Run Tests
      #script:
      #  - sudo apt install maven
      #  - mvn test

deploy:
  provider: script
  script: bash scripts/deploy_docker
  on:
    branch:
      master