server:
  error:
    include-message: on_param

spring:
  api:
    key: ${API_KEY}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: root
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      password: ${SECURITY_PASSWORD}
    origins: ${KNOWN_ORIGINS}

# pages to query from, see data
# updater class for more info
#
page:
  range:
    start: ${PAGE_START}
    end: ${PAGE_END}