server:
  error:
    include-message: always

spring:
  api:
    key: ### PUT THE KEY FOR THE API HERE ###
  datasource:
    url: ### jdbc mysql database link ###
    username: ### username for logging into the database ###
    password: ### password to access the database with ###
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      password: ### password for spring security ###
    origins: ### allowed origins by CORS ###

year:
  range:
    start: ### start date to query interest rates from ###
    end: ### end date to query interest rates from ###
