name: Build and Push Docker Image 

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Log in to Docker Hub
        run: echo $DOCKER_TOKEN | docker login -u flo456123 --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t flo456123/private:back-bond \
            --push .

      - name: Clean up
        run: docker buildx rm